name: miniapp
description: "Augmentek - Инструменты усиления человеческого интеллекта"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.3
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  logger: ^2.0.2+1
  telegram_web_app: ^0.1.1
  go_router: ^14.2.0
  shared_preferences: ^2.2.2
  firebase_core: ^3.3.0
  firebase_auth: ^5.2.0
  firebase_analytics: ^11.3.3
  cloud_firestore: ^5.1.0
  cloud_functions: ^5.1.0
  firebase_storage: ^12.2.0
  js: ^0.7.2
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.4
  
  # Utils
  flutter_secure_storage: ^4.2.1
  cached_network_image: ^3.3.0
  flutter_markdown: ^0.6.18
  url_strategy: ^0.3.0
  http: ^1.4.0
  dio: ^5.4.0
  
  # File handling
  dotted_border: ^2.1.0
  auto_size_text: ^3.0.0
  youtube_player_flutter: ^9.0.3
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  freezed: ^2.4.6

flutter:
  uses-material-design: true
